### ISSUE TITLE
pull_commits returns a mix of github handles and display names

### ISSUE THREAD

**Issue by epijim** [r-world-devs/GitStats#332]
The results of pull_commits give a mixture of github handles and display names, this makes it hard to work with. 

Is this due to logic around plugging in display name from git where it doesn't know the github user?

**Comment by maciekbanas** [comment]
Hi James @epijim thanks for the question.

As I see this is mainly problem with GitLab - basically I take directly the data from `commit API` - the `author name` field, and for some reason some commits are logged with a full name and some with logins. So it seems it may be the reason you describe, git plugs in the display name instead of user.

**Comment by maciekbanas** [comment]
@epijim I think we can solve it with a fast iteration over unique names from commits with search API. The process would go after pulling commits response. Search API would look up for the authors in `scope:users` and pull the login separately and user name. In case search results are multiple, `GitStats` would precisely match the author to the name or login.

The resulting commits table would then have 2 additional columns: `author_login` and `author_name`. Sometimes, in case it can not find the user in API, a `NA` would be applied.

**Comment by epijim** [comment]
this sounds perfect! thanks Maciej
