### ISSUE TITLE
Handle getting users' repos

### ISSUE THREAD

**Issue by epijim** [r-world-devs/GitStats#492]
I found a weird issue that only seems to impact only @ddsjoberg's repos 

```r
  git_stats <- GitStats::create_gitstats() |>
    GitStats::set_github_host(
      repos = "ddsjoberg/gtsummary",
      token = Sys.getenv("GITHUB_PAT")
    ) |>
    GitStats::get_repos(progress = TRUE)
```

Gives an error:

```r
Error in `purrr::map()`:
ℹ In index: 1.
Caused by error in `purrr::map()`:
ℹ In index: 1.
Caused by error in `UseMethod()`:
! no applicable method for 'filter' applied to an object of class "NULL"
```

**Comment by epijim** [comment]
other repos all work fine 🤷🏽

**Comment by ddsjoberg** [comment]
I took a quick look. This issue appears here
https://github.com/r-world-devs/GitStats/blob/08a7d85e63eb3f71933e3531b09ff7591c0ce199/R/GitHost.R#L608

The repo name is defined. BUT when  the `repos_table` object is created, it's returning an empty list instead of the full information about all the repos in the org. Thus when we get to the lines below, the `repos` is defined, but then we try to use both `repos_table` and `repos`. 

```r
        if (!is.null(repos)) {
          repos_table <- repos_table %>%
            dplyr::filter(repo_name %in% repos)
        }
```

A quick fix could be to simply add `if (!is.null(repos) && !is.null(repos_table))` but I didn't investigate much what information is in `repos_table` and how it's used. 

Perhaps one reason `repos_table` is not populated, is because these are not coming from a proper GH organization, and rather a individual account?

**Comment by maciekbanas** [comment]
Thanks @epijim  @ddsjoberg,  I’ll take a look into it. I’m currently preparing a patch release with another bugfix and will include this issue in it as well.

**Comment by maciekbanas** [comment]
@ddsjoberg yes, it looks like GitStats does not support getting repositories from a individual user.
Tried this one, also fails:
```
create_gitstats() |>
  set_github_host(
    repos = "hadley/elmer",
    token = Sys.getenv("GITHUB_PAT")
  ) |>
  get_repos(progress = TRUE)

```

**Comment by maciekbanas** [comment]
This is because of the construction of GraphQL query for getting repositories. I will try to adjust it to get repositories by users also.
